initial templates
trapacska/templates pull request #1
Opened 2019-01-28 09:33 UTC by trapacska

2019-01-28 09:38 UTC, trapacska commented on steps/README.md
> +## About
I how to run this step section should not include other ways to run the step than with the CLI. Not sure if contribution and how to use sections should be in separate source as shared, and that info maybe listed under the about section?

2019-01-28 10:23 UTC, godrei commented on steplib/README.md
> +<h4 align="center">Bitrise StepLib is our versioned collection of our Steps.<br>This is the repository that all of our Steps that is visible in our <a href="https://www.bitrise.io/features/workflow-e
I would only use the first sentence with a slight modification:

`Bitrise StepLib is a versioned collection of the Bitrise Steps.` 

As it contains contributed steps as well. 

I think it does worth to mention the second sentence, but may i would mention that the visual representation of the setplib can be found here: https://www.bitrise.io/integrations/steps
(i would try to form a better sentence for this)

2019-01-28 10:33 UTC, lpusok commented on steplib/README.md
> +Feel free to send us feedback on [Twitter](https://twitter.com/bitrise) or [file an issue](https://github.com/bitrise-io/bitrise/issues/new). Feature requests, pull requests are always welcome. If yo
Is there a contribution section?

2019-01-28 10:35 UTC, lpusok commented on steplib/README.md
> +<h4 align="center">Bitrise StepLib is our versioned collection of our Steps.<br>This is the repository that all of our Steps that is visible in our <a href="https://www.bitrise.io/features/workflow-e
Is it a good idea to use "our"? It may not be clear what it refers to without context.

2019-01-28 10:36 UTC, godrei commented on steplib/README.md
> +# How to share a new Step or a new version of a Step
Do not forget to mention that a step veresion reflects a step repository tag, so first tag the actual state of the repo.

Link the step template repo's share-this-step wf

I would not mention how to run a workflow here

2019-01-28 10:38 UTC, godrei commented on steplib/README.md
> +When you have a Step repository you can share that to our StepLib so it will become visible in our Workflow Editor and in the `bitrise.yml`. When you share your step we store a copy of your `step.yml
Mention what is that small change as it describes why re-share necessary when step.yml change is required

2019-01-28 10:38 UTC, lpusok commented on steps/README.md
> +## How to run this step
Could move this up, based on https://github.com/noffle/art-of-readme

2019-01-28 10:39 UTC, godrei commented on steplib/README.md
> +# Requirements
ohh i would either integrate it into the `share step` section or move it before that section

2019-01-28 10:40 UTC, godrei commented on steplib/README.md
> +# How to share a new Step or a new version of a Step
Also include the PR checklist

2019-01-28 10:40 UTC, lpusok commented on steps/README.md
> +> This step will build a Flutter project
Should not refer to step, as it may not be clear what a step is. And the code is usable "as is"

2019-01-28 10:52 UTC, godrei commented on steps/README.md
> +1. Send a PR to our team
Submit a PR

2019-01-30 08:47 UTC, godrei commented on tools_and_plugins/README.md
> +<h4 align="center">Bitrise CLI is a Command Line Interface for running your Workflows and automate your local development processes (or almost anything) with a single terminal command. To see which s
i would remove the second sentence

2019-01-30 08:48 UTC, godrei commented on tools_and_plugins/README.md
> +Some of our sub-sites if you are new to Bitrise and want read more about Workflows, Steps and our products:
i would remove this, or move this to a section somewhere below this

2019-01-30 08:49 UTC, godrei commented on tools_and_plugins/README.md
> +# Feedback
i would move this below install and usage sections, somewhere around contribution

2019-01-30 08:50 UTC, godrei commented on tools_and_plugins/README.md
> +#### From source (You'll need Go):
i would remove this (if you want just use it, then use brew, or binary install), if you want to modify it then fork it and clone...

2019-01-30 08:51 UTC, godrei requested changes
please have a look at my notes

2019-01-31 10:15 UTC, lszucs commented
👀 I checked it out, nothing to add to previous comments :)

2019-02-01 10:03 UTC, trapacska commented on steplib/README.md
> +Feel free to send us feedback on [Twitter](https://twitter.com/bitrise) or [file an issue](https://github.com/bitrise-io/bitrise/issues/new). Feature requests, pull requests are always welcome. If yo
there is no contribution to our steplib but anyone can send in new steps or step versions

2019-02-01 10:16 UTC, trapacska commented on steps/README.md
> +> This step will build a Flutter project
these infos are generated from the step.yml

2019-02-01 10:39 UTC, godrei commented on steplib/README.md
> +<h4 align="center">Bitrise StepLib is our versioned collection of the Bitrise Steps.<br>This is the repository that all of our Steps that is visible in our <a href="https://www.bitrise.io/features/wo
I would only use the first sentence with a slight modification:

`Bitrise StepLib is a versioned collection of the Bitrise Steps.` 

As it contains contributed steps as well. 

I think it does worth to mention the second sentence, but may i would mention that the visual representation of the setplib can be found here: https://www.bitrise.io/integrations/steps
(i would try to form a better sentence for this)

2019-02-01 10:42 UTC, godrei commented on steplib/README.md
> +# Requirements
move this section to the contribution guide. Now part of the contribution is here, another part is somewhere else.

2019-02-01 10:51 UTC, lpusok commented on steplib/README.md
> +Feel free to send us feedback on [Twitter](https://twitter.com/bitrise) or [file an issue](https://github.com/bitrise-io/bitrise/issues/new). Feature requests, pull requests are always welcome. If yo
the text above refers to it tough

2019-02-01 10:53 UTC, godrei commented on steplib/README.md
> +# Feedback
why is feedback in the first section?

2019-02-01 10:55 UTC, godrei commented on steplib/README.md
> +# Requirements
move the step share guide in this template

2019-02-01 11:01 UTC, godrei requested changes
Step and Tool READMEs looks great to me,
i have suggested some changes for the StepLib README.

2019-02-01 15:05 UTC, merged